### ISSUE TITLE
CezerinClient is not a constructor

### ISSUE THREAD

**Issue by inspireui** [cezerin/client#4]
Hi, i've got this issue when run the project, please suggest, it worked fine on last few days a go but when update the cezerin-client it show this error.

<img width="944" alt="screen shot 2018-08-23 at 10 31 00 am" src="https://user-images.githubusercontent.com/29778334/44503328-f558c500-a6bf-11e8-9dbd-7d963af35dc8.png">

**Comment by sonufrienko** [comment]
@inspireui 
Please, check the new version.
